---
title: Office of Civic Innovation
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: "/:collection/:path/"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: projects
  values:
    layout: sidebar-page
    nav_from_collection: projects
    image_path: "/assets/img/projects/project-tile-placeholder.jpg"
email: ipoall@louisvilleky.gov
description: 'The Louisville Metro Innovation Team was established in
 2011 as part of the pioneer cohort of Bloomberg innovation teams.
 While funded by Bloomberg, the i-team took on challenges such as
 Vacant & Abandoned Properties, Wet/Dry Recycling, Public Wifi, and
 Corrections. This work supported Mayor Fischer's overall strategy
 for the city by working on some of the biggest identified challenges
 in Louisville Metro as a community and as an enterprise. In 2015,
 the Bloomberg funding ended and the i-team merged with the
 Office of Performance Improvement to become the
 Office of Performance Improvement and Innovation (OPI2).


Since 2015, the i-team has focused on community-focused technology projects,
also known as Smart City projects. These projects aim to transform our government's
relationship with the community and to transform government operations through
the effective use of technology and data. Some of our initiatives include the
CNET Smart Apartment, which allows us to test how the Smart City and the Smart Home
will interact, Waze Data Partnership, which allows us to understand the real-time
and historical traffic issues in our community, and Digital Inclusion, which
seeks to increase equity in regards to access to technology and the internet.
'
baseurl:
url: http://projects.lsvll.io
twitter:
  username: OPI2Lou
medium_url: https://medium.com/louisville-metro-opi2
zilker_theme: light
markdown: kramdown
gems:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-redirect-from
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
sass:
  sass_dir: assets/stylesheets/
permalink: pretty
exclude:
- node_modules
- gulpfile.js
- Gemfile
- Gemfile.lock
- npm-debug.log
- "/screenshots"
- "/assets/stylesheets/bourbon"
- "/assets/stylesheets/bourbon-neat"
- "/assets/uswds/stylesheets"
- "/assets/uswds/js"
- ".bundle"
- "/vendor"
- _bourbon
- _bourbon-neat
- _uswds
